import { FormField } from "../Utilities/FormField";
import {
  createTextField,
  createDateField,
  createRadioField,
  createSelectField,
  createEmailField,
} from "../Utilities/formUtilities";
import { ParticipationFormData } from "./ParticipationFormSchema";

export const participationFormFields: FormField<ParticipationFormData>[] = [
  createTextField("firstName", "First Name"),
  createTextField("middleName","Middle Name"),
  createTextField("lastName", "Last Name"),
  createTextField("preferredName","Peffered Name"),
  createTextField("studentId","Student Id"),
  createSelectField("gradeLevel","Current Grade Level",[
    { label: "", value: "" }, 
    { label: "7th Grade", value: "7th grade" },
    {label:"8th Grade",value:"8th grade"},
    {label:"Freshman",value:"Freshman"},
    {label:"Sophomore",value:"Sophomore"},
    {label:"Junior",value:"Junior"},
    {label:"Senior",value:"Senior"},
  ]),
  createSelectField("gender", "Gender", [
    { label: "", value: "" }, 
    { label: "Male", value: "Male" },
    { label: "Female", value: "Female" },
    { label: "Other", value: "Other" },
    {label:"Non-Binary",value:"NonBinary"},
    { label: "Prefer not to say", value: "Prefer not to say" },
  ]),
  createRadioField("numberOfParents","Number of Parents",[
    { label: "", value: "" }, 
    {label:"One",value:"One"},
    {label:"Two",value:"Two"},
    {label:"Other",value:"other"},
  ]),
  createTextField("studentPhone","Student Phone Number"),
  createEmailField("studentEmail","Student Email"),
  createTextField("street","Street"),
  createTextField("city","City"),
  createTextField("state","State"),
  createTextField("zipcode","Zip Code"),
  createSelectField("race", "Race", [
    { label: "", value: "" }, 
    { label: "American Indian/Alaskan Native", value: "American Indian/Alaskan Native" },
    { label: "Asian", value: "Asian" },
    { label: "White", value: "White" },
    {label:"Black/African American",value:"Black/African American"},
    { label: "Hispanic/Latino", value: "Hispanic/Latino" },
    { label: "Other", value: "Other" },
  ]),
  createSelectField("language", "Language that you used the most", [
    { label: "", value: "" }, 
    { label: "English", value: "English" },
    { label: "Mandarin Chinese", value: "Mandarin Chinese" },
    { label: "Hindi", value: "Hindi" },
    {label:"Spanish",value:"Spanish"},
    { label: "French", value: "French" },
    { label: "Modern Standard Arabic", value: "Modern Standard Arabic" },
    { label: "Bengali", value: "Bengali" },
    { label: "Russian", value: "Russian" },
    { label: "Portuguese", value: "Portuguese" },
    {label:"Urdu",value:"Urdu"},
    { label: "Indonesian", value: "Indonesian" },
    { label: "German", value: "German" },
    { label: "Japanese", value: "Japanese" },
    { label: "Nigerian Pidgin", value: "Nigerian Pidgin" },
    { label: "Marathi", value: "Marathi" },
    {label:"Telugu",value:"Telugu"},
    { label: "Turkish", value: "Turkish" },
    { label: "Tamil", value: "Tamil" },
    { label: "Yue Chinese", value: "Yue Chinese" },
    { label: "Vietnamese", value: "Vietnamese" },
    { label: "Tagalog", value: "Tagalog" },
    {label:"Wu Chinese",value:"Wu Chinese"},
    { label: "Korean", value: "Korean" },
    { label: "Iranian Persian(Farsi)", value: "Iranian Persian(Farsi)" },
    { label: "Hausa", value: "Hausa" },
    { label: "Egyptian Spoken Arabic", value: "Egyptian Spoken Arabic" },
    { label: "Swahili", value: "Swahili" },
    {label:"Javanese",value:"Javanese"},
    { label: "Italian", value: "Italian" },
    { label: "Western Punjabi", value: "Western Punjabi" },
    { label: "Kannada", value: "Kannada" },
    { label: "Gujarati", value: "Gujarati" },
    { label: "Thai", value: "Thai" },
    {label:"Other",value:"Other"},
  ]),
  createSelectField("proficiency", "Proficiency in the primary langauge", [
    { label: "", value: "" }, 
    { label: "Proficient", value: "Proficient" },
    { label: "Moderate", value: "Moderate" },
    { label: "Poor", value: "Poor" },
  ]),
  createSelectField("secondaryLanguage", "Secondary Language used at home", [
    { label: "", value: "" }, 
    { label: "English", value: "English" },
    { label: "Mandarin Chinese", value: "Mandarin Chinese" },
    { label: "Hindi", value: "Hindi" },
    {label:"Spanish",value:"Spanish"},
    { label: "French", value: "French" },
    { label: "Modern Standard Arabic", value: "Modern Standard Arabic" },
    { label: "Bengali", value: "Bengali" },
    { label: "Russian", value: "Russian" },
    { label: "Portuguese", value: "Portuguese" },
    {label:"Urdu",value:"Urdu"},
    { label: "Indonesian", value: "Indonesian" },
    { label: "German", value: "German" },
    { label: "Japanese", value: "Japanese" },
    { label: "Nigerian Pidgin", value: "Nigerian Pidgin" },
    { label: "Marathi", value: "Marathi" },
    {label:"Telugu",value:"Telugu"},
    { label: "Turkish", value: "Turkish" },
    { label: "Tamil", value: "Tamil" },
    { label: "Yue Chinese", value: "Yue Chinese" },
    { label: "Vietnamese", value: "Vietnamese" },
    { label: "Tagalog", value: "Tagalog" },
    {label:"Wu Chinese",value:"Wu Chinese"},
    { label: "Korean", value: "Korean" },
    { label: "Iranian Persian(Farsi)", value: "Iranian Persian(Farsi)" },
    { label: "Hausa", value: "Hausa" },
    { label: "Egyptian Spoken Arabic", value: "Egyptian Spoken Arabic" },
    { label: "Swahili", value: "Swahili" },
    {label:"Javanese",value:"Javanese"},
    { label: "Italian", value: "Italian" },
    { label: "Western Punjabi", value: "Western Punjabi" },
    { label: "Kannada", value: "Kannada" },
    { label: "Gujarati", value: "Gujarati" },
    { label: "Thai", value: "Thai" },
    {label:"Other",value:"Other"},
  ]),
  createSelectField("proficiencyInSecondaryLanguage", "Proficiency in the secondary langauge", [
    { label: "", value: "" }, 
    { label: "Proficient", value: "Proficient" },
    { label: "Moderate", value: "Moderate" },
    { label: "Poor", value: "Poor" },
  ]),
  createSelectField("thirdLanguage", "Third Language used at home", [
    { label: "", value: "" }, 
    { label: "English", value: "English" },
    { label: "Mandarin Chinese", value: "Mandarin Chinese" },
    { label: "Hindi", value: "Hindi" },
    {label:"Spanish",value:"Spanish"},
    { label: "French", value: "French" },
    { label: "Modern Standard Arabic", value: "Modern Standard Arabic" },
    { label: "Bengali", value: "Bengali" },
    { label: "Russian", value: "Russian" },
    { label: "Portuguese", value: "Portuguese" },
    {label:"Urdu",value:"Urdu"},
    { label: "Indonesian", value: "Indonesian" },
    { label: "German", value: "German" },
    { label: "Japanese", value: "Japanese" },
    { label: "Nigerian Pidgin", value: "Nigerian Pidgin" },
    { label: "Marathi", value: "Marathi" },
    {label:"Telugu",value:"Telugu"},
    { label: "Turkish", value: "Turkish" },
    { label: "Tamil", value: "Tamil" },
    { label: "Yue Chinese", value: "Yue Chinese" },
    { label: "Vietnamese", value: "Vietnamese" },
    { label: "Tagalog", value: "Tagalog" },
    {label:"Wu Chinese",value:"Wu Chinese"},
    { label: "Korean", value: "Korean" },
    { label: "Iranian Persian(Farsi)", value: "Iranian Persian(Farsi)" },
    { label: "Hausa", value: "Hausa" },
    { label: "Egyptian Spoken Arabic", value: "Egyptian Spoken Arabic" },
    { label: "Swahili", value: "Swahili" },
    {label:"Javanese",value:"Javanese"},
    { label: "Italian", value: "Italian" },
    { label: "Western Punjabi", value: "Western Punjabi" },
    { label: "Kannada", value: "Kannada" },
    { label: "Gujarati", value: "Gujarati" },
    { label: "Thai", value: "Thai" },
    {label:"Other",value:"Other"},
  ]),

  createTextField("primaryParentFirstName", "Primary Parent First Name"),
  createTextField("primaryParentMiddleName", "Primary Parent Middle Name"),
  createTextField("primaryParentLastName", "Primary Parent Last Name"),
  createSelectField("primaryParentRelationship", "Primary Parent's Relationship to the Student", [
    { label: "", value: "" }, 
    { label: "Mother", value: "Mother" },
    { label: "Father", value: "Father" },
    { label: "Grandparent", value: "Grandparent" },
    {label:"Aunt/Uncle",value:"Aunt/Uncle"},
    { label: "Foster Parent", value: "Foster Parent" },
    { label: "Other", value: "Other" },
  ]),

  createDateField("primaryParentBirthDate", "Primary Parent Birth Date"),
  createTextField("primaryParentStreet", "Street (Primary Parent)"),
  createTextField("primaryParentCity", "City (Primary Parent)"),
  createTextField("primaryParentState", "State (Primary Parent)"),
  createTextField("primaryParentZipCode", "Zip Code (Primary Parent)"),
  createTextField("primaryParentPhoneNumber", "Primary Parent Phone Number"),
  createEmailField("primaryParentEmail", "Primary Parent Email"),

  createRadioField("primaryParentEnglishProficiency", "Primary Parent English Proficiency", [
    { label: "", value: "" }, 
    { label: "Poor", value: "Poor" },
    { label: "Moderate", value: "Moderate" },
    { label: "Proficient", value: "Proficient" },
  ]),
  createSelectField("primaryParentEducation", "Primary Parent Education", [
    { label: "", value: "" }, 
    { label: "No High School Diploma", value: "No High School Diploma" },
    { label: "High School Diploma", value: "High School Diploma" },
    { label: "Associate", value: "Associate" },
    { label: "College Degree", value: "College Degree" },
  ]),

  createRadioField("primaryParentEmploymentStatus", "Primary Parent Employment Status", [
    { label: "", value: "" }, 
    { label: "Full Time (35+ hours)", value: "Full Time" },
    { label: "Part Time / Training", value: "Part Time" },
    { label: "Unemployed", value: "Unemployed" },
  ]),

  


  createTextField("secondaryParentFirstName", "Secondary Parent First Name"),
  createTextField("secondaryParentMiddleName", "Secondary Parent Middle Name"),
  createTextField("secondaryParentLastName", "Secondary Parent Last Name"),
  createSelectField("secondaryParentRelationship", "Secondary Parent's Relationship to the Student", [
    { label: "", value: "" }, 
    { label: "Mother", value: "Mother" },
    { label: "Father", value: "Father" },
    { label: "Grandparent", value: "Grandparent" },
    {label:"Aunt/Uncle",value:"Aunt/Uncle"},
    { label: "Foster Parent", value: "Foster Parent" },
    { label: "Other", value: "Other" },
  ]),

  createDateField("secondaryParentBirthDate", "Secondary Parent Birth Date"),
  createTextField("secondaryParentStreet", "Street (Primary Parent)"),
  createTextField("secondaryParentCity", "City (Primary Parent)"),
  createTextField("secondaryParentState", "State (Primary Parent)"),
  createTextField("secondaryParentZipCode", "Zip Code (Primary Parent)"),
  createTextField("secondaryParentPhoneNumber", "Secondary Parent Phone Number"),
  createEmailField("secondaryParentEmail", "Secondary Parent Email"),

  createRadioField("secondaryParentEnglishProficiency", "Secondary Parent English Proficiency", [
    { label: "", value: "" }, 
    { label: "Poor", value: "Poor" },
    { label: "Moderate", value: "Moderate" },
    { label: "Proficient", value: "Proficient" },
  ]),
  createSelectField("secondaryParentEducation", "Secondary Parent Education", [
    { label: "", value: "" }, 
    { label: "No High School Diploma", value: "No High School Diploma" },
    { label: "High School Diploma", value: "High School Diploma" },
    { label: "Associate", value: "Associate" },
    { label: "College Degree", value: "College Degree" },
  ]),

  createRadioField("secondaryParentEmploymentStatus", "Secondary Parent Employment Status", [
    { label: "", value: "" }, 
    { label: "Full Time (35+ hours)", value: "Full Time" },
    { label: "Part Time / Training", value: "Part Time" },
    { label: "Unemployed", value: "Unemployed" },
  ]),

   createTextField("emergencyContactName","Emergency Contact Name"),
   createTextField("emergencyContactPhoneNumber","Emergency Contact Phone Number"),

   createRadioField("schoolLunch", "School Lunch", [
    { label: "", value: "" }, 
    { label: "Full Pay", value: "Full Pay" },
    { label: "Free/Reduced", value: "Free/Reduced" },
  ]),

  createSelectField("disability", "Does your child have a disability (diagnosed by a doctor specialist)?", [
    { label: "", value: "" }, 
    { label: "Yes", value: "Yes" },
    { label: "No", value: "No" },
  ]),
  createSelectField("IEP_IFSP", "Does the student have IEP or IFSP?", [
    { label: "", value: "" }, 
    { label: "Yes", value: "Yes" },
    { label: "No", value: "No" },
  ]),
  createTextField("specificDisability","If the student has IEP or IFSP, please list the specific disability"),

  createSelectField("concerns", "If the student has IEP or IFSP, please list the specific disability", [
    { label: "", value: "" }, 
    { label: "None", value: "None" },
    { label: "Hearing", value: "Hearing" },
    { label: "Vision", value: "Vision" },
    { label: "Obesity", value: "Obesity" },
    { label: "Allergies", value: "Allergies" },
    { label: "Asthma", value: "Asthma" },
    { label: "Dental Problems", value: "Dental" },
    { label: "Other", value: "Other" },
  ]),

  createTextField("otherConcerns","If you have other concerns about your student, please describe"),
  createTextField("medicalProblem","Describe any Medical Problems your student has"),
  createTextField("developmentConcern","Describe any developmental concerns you have about your student"),
  createTextField("speechIssue","Describe any speech or language development issues your student has"),
  createTextField("physicalDevelopment","Describe any physical development issues your student has"),

];
